# Site wide configuration

title: "TheDiamondPicks"
description: "TheDiamondPicks' Personal Website"
#if you modify locale please have a look at _data/messages.yml too
locale: en
#for meta name="author" :
author: "TheDiamondPicks"

#Target date in UTC / GMT
countdown:
  theme: red
  year: 2016
  month: 1
  day: 1
  hour: 12
  minute: 0

# Site owner
owner:
  name: TheDiamondPicks
  email:
  twitter:
  google-plus:
  instagramm:
  #Aboutlink = German "Impressum", provide url and caption (eg "Impressum")
  aboutlink:
    url:
    caption:


# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
