name: TheDiamondPicks
description: Hello my name is TheDiamondPicks. I am a software developer with experience in Java, HTML, PHP, VB.NET, CSS, Bootstrap and Bukkit. I enjoy programming and I currently work for fun and therefore I do work for free. Feel free to contact me if you wish to have work done (Within the realms of reason (e.g. No large MC minigames!)).
paginate: 10
highlighter: rouge
markdown: kramdown